version: '3.5'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

nestjs-app:
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: database
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "3000:3000"
  depends_on:
    - postgres
  volumes:
    - ./src:/app/src  

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres:
    driver: local
